---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  become_user: root
  # vars:
  #  user: admin
  tasks:
  - name: Create user
    user: name="{{ user }}" state=present
    register: output
  
  - name: Set password for the user
    shell: echo "{PASSWORD}" | passwd "{{ user }}" --stdin
    
  - name: debug
    debug:
      msg: \"{{ user }}\" has been added successfully.
    
